name: openfe-notebooks
channels:
  - conda-forge
dependencies:
  - coverage
  - ipywidgets
  - lxml
  - nbval
  - nglview
  - notebook
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - python
  - gufe >=1.7.0, <1.8.0
  - openfe==1.8.0
